apiVersion: v1
kind: Service
metadata:
    name: spring-app-service
    labels:
        name: spring-app-service
        app: demo-spring-app
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30005
    selector:
        name: spring-app-pod
        app: demo-spring-app