apiVersion: v1
kind: Service
metadata:
    name: postgres-container
    labels:
        name: postgres-service
        app: demo-spring-app
spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        name: postgres-pod
        app: demo-spring-app